---
server:
  port: "8081"

basyx:
  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD"
  aasrepository:
    feature:
      registryintegration: "http://aas-registry:8080"
  environment: "file:aas"
  submodelrepository:
    feature:
      registryintegration: "http://submodel-registry:8080"
  externalurl: "http://localhost:8081"
