name: Python Package

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[test]

      - name: Lint with flake8
        run: |
          flake8

      - name: Start BaSyx stack
        run: docker compose -f compose.yaml up -d

      - name: Wait for BaSyx to be ready
        run: |
          SECONDS=0
          until curl -sSf http://localhost:8081/actuator/health || [ "$SECONDS" -gt 90 ]; do
            echo "Waiting for AAS Environment... Elapsed: $SECONDS seconds"
            sleep 3
          done

          if [ "$SECONDS" -gt 90 ]; then
            echo "❌ Timeout: AAS Environment not reachable after 90 seconds."
            docker compose logs
            exit 1
          fi

      - name: Test with pytest
        run: |
          pytest --cov --cov-fail-under=50 --cov-branch --cov-report=xml --cov-report=term

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4

      - name: Run command line script
        run: |
          aas info
